# Generated by Django 5.2.8 on 2025-12-31 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recomendación'),
        ),
    ]
