# Generated by Django 5.2.8 on 2025-12-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0002_alter_genero_creado_alter_pelicula_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(),
        ),
    ]
