# Generated by Django 5.2.8 on 2026-01-06 21:45

import primeraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0003_alter_comentario_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='foto',
            field=models.ImageField(default='listar_peliculas/pelicula.png', null=True, upload_to=primeraApp.models.Pelicula.generarNombre),
        ),
    ]
