# Generated by Django 5.2.8 on 2026-01-07 21:16

import primeraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0004_pelicula_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='foto',
            field=models.ImageField(default='peliculas/pelicula.png', null=True, upload_to=primeraApp.models.Pelicula.generarNombre),
        ),
    ]
